spring:
  profiles:
    active: dev,debug
---

spring:
  profiles: debug
debug: true
logging:
  level:
    com.metafour: DEBUG
---

spring:
  profiles: dev
server:
  port: 8080
---

spring:
  profiles: prod
server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-password: changeit
logging:
  level:
    com.metafour: INFO
---

spring:
  datasource:
    url: jdbc:h2:file:/tmp/mrouter
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
---

spring:
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
---

mrouter:
  users:
    - code: mrouter
      password: cDG63SDeEDQyT?84
      roles: [USER]
    - code: admin
      password: R3p0r7V!ew
      roles: [ADMIN, USER]
    - code: sadmin
      password: 123
      roles: [SADMIN, ADMIN, USER]
---

mtrak:
  otherInis:
    - codes:
        - twc
      prefix: https://test-ncpg.netcourier.net/mtrak/
      suffix: .ini
